/*
 * @Author: tonyTang 
 * @Date: 2018-10-17 18:07:57 
 * @Last Modified by: tonyTang
 * @Last Modified time: 2018-10-20 20:18:14
 */

export const SET_CHANGEHOMECOMPONENTSHOW = 'SET_CHANGEHOMECOMPONENTSHOW';
export const SET_CHANGEHOMERIGHTSHOW = 'SET_CHANGEHOMERIGHTSHOW';
export const SET_CHANGEGAMECENTERSHOW = 'SET_CHANGEGAMECENTERSHOW';

//看是否需要删除下面四条
export const SET_CHANGECOINCENTERSHOW = 'SET_CHANGECOINCENTERSHOW';
export const SET_CHANGECOINRIGHTSHOW = 'SET_CHANGECOINRIGHTSHOW';
export const SET_CHANGEROLLERCOASTERCENTERSHOW = 'SET_CHANGEROLLERCOASTERCENTERSHOW';
export const SET_CHANGEROLLERCOASTERRIGHTSHOW = 'SET_CHANGEROLLERCOASTERRIGHTSHOW';

export const SET_CHANGECOMMONPROBLEMSHOW = 'SET_CHANGECOMMONPROBLEMSHOW';
export const SET_CHANGEABOUTSSHOW = 'SET_CHANGEABOUTSSHOW';
export const SET_CHANGENAVLIST = 'SET_CHANGENAVLIST';

export const SET_USERNAME = 'SET_USERNAME';
export const SET_SCATTER = 'SET_SCATTER';
export const SET_EOSCLIENT = 'SET_EOSCLIENT';
export const SET_LOGINSTATUS = 'SET_LOGINSTATUS';
export const SET_LOGINOUTTEXT = 'SET_LOGINOUTTEXT';
export const SET_LOGINTEXT = 'SET_LOGINTEXT';
export const SET_VILLAGEDETAILSHOW = 'SET_VILLAGEDETAILSHOW';
export const SET_INVITEFRIENDSHOW = 'SET_INVITEFRIENDSHOW';
export const SET_FRIENDRECORDSSHOW = 'SET_FRIENDRECORDSSHOW';
export const SET_VILLAGEHOMESHOW = 'SET_VILLAGEHOMESHOW';

//设置抛硬币和过山车游戏展示状态
export const SET_COINGAMESHOW = 'SET_COINGAMESHOW';
export const SET_ROLLGAMESHOW = 'SET_ROLLGAMESHOW';

//设置抛硬币和过山车公共部分数据，account表中的数据
export const SET_COMMONCOINOBJ = 'SET_COMMONCOINOBJ';
export const SET_COMMONROLLOBJ = 'SET_COMMONROLLOBJ';

//设置抛硬币和过山车公共部分数据，gbdata表中的数据
export const SET_GBDATACOINOBJ = 'SET_GBDATACOINOBJ';
export const SET_GBDATAROLLOBJ = 'SET_GBDATAROLLOBJ';

//设置抛硬币游戏的历史数据列表和我的游戏历史数据列表
export const SET_HISTORYDATA = 'SET_HISTORYDATA';
export const SET_MYHISTORY = 'SET_MYHISTORY';
//设置我的历史记录的第一条的id.
export const SET_ZEROITEMID = 'SET_ZEROITEMID';

//设置过山车游戏的历史数据列表和我的游戏历史数据列表
export const SET_ROLLHISTORYLIST = 'SET_ROLLHISTORYLIST';
export const SET_ROLLMYHISTORYLIST = 'SET_ROLLMYHISTORYLIST';
//设置过山车我的历史记录的第一条的id.
export const SET_ROLLZEROITEMID = 'SET_ROLLZEROITEMID';